version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install
      - run:
          name: start tests
          command: npm start